resources:
  - certificate.yaml
  - issuer.yaml
  - viz-ingress.yaml

generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: webhook-issuer-tls
    namespace: linkerd
    type: kubernetes.io/tls
    files:
      - tls.key=./root-cert/issuer.key
      - tls.crt=./root-cert/issuer.crt
  - name: webhook-issuer-tls
    namespace: linkerd-viz
    type: kubernetes.io/tls
    files:
      - tls.key=./root-cert/issuer.key
      - tls.crt=./root-cert/issuer.crt
  - name: webhook-issuer-tls
    namespace: linkerd-jaeger
    type: kubernetes.io/tls
    files:
      - tls.key=./root-cert/issuer.key
      - tls.crt=./root-cert/issuer.crt
